fix ORACLE_REGIONS in scheduler script

diff --git a/jenkins/groovy/set-release-ga/Jenkinsfile b/jenkins/groovy/set-release-ga/Jenkinsfile
--- a/jenkins/groovy/set-release-ga/Jenkinsfile
+++ b/jenkins/groovy/set-release-ga/Jenkinsfile
@@ -41,8 +41,11 @@ ENVIRONMENT=${environment} scripts/versioning-manager.sh
 def addLiveLocalPoolsToScheduler(environment, release_number) {
     sh(
         script: """#!/bin/bash
-LOCAL_PATH=\$(dirname "\${BASH_SOURCE[0]}")
-[ -e \$LOCAL_PATH/../clouds/all.sh ] && . \$LOCAL_PATH/../clouds/all.sh
+. clouds/all.sh
+if [ -z "\$ORACLE_REGIONS" ]; then
+    echo "## addLiveLocalPoolsToScheduler failed to load ORACLE_REGIONS
+    exit 1
+fi
 for REGION in \$ORACLE_REGIONS; do
     JVB_GROUPS="\$(ALL_RELEASES=true ORACLE_REGION=\${REGION} scripts/custom-autoscaler-list-groups.sh)"
     if [[ \${#JVB_GROUPS} != 0 ]]; then
